# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               My Tech Journey
tagline:             'A blog by João Almeida'
description:         ''
url:                 http://joao-m-almeida.github.io/
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              João Almeida
  url:               http://joao-m-almeida.github.io/
  email:             jmirandadealme@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
markdown: kramdown
